### PR TITLE
ltcd: Add support for Litecoin mainnet

### PR DESCRIPTION
**Pull request by coblee**

### CODE REVIEW

**Comment by coblee** [comment]
@Roasbeef I created a new pull request. This is syncing MainNet fine on my computer.

**Review by Roasbeef — COMMENTED** [review]
Changes look good to me! 

Kicked off a sync locally to confirm we reach tip without any issues, after the successful sync, I'll LGTM and get this merged.

**Comment by coblee** [comment]
awesome. thanks

**Review by Roasbeef — APPROVED** [review]
LGTM 🐔

**Pull request merged**
